<a href="https://colab.research.google.com/github/JustineCole/UtilizationManagement/blob/main/20230521_DLM_Explore_and_Clean.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Setup

In [1]:
import os
from google.colab import drive
drive.mount('/content/drive/')
os.chdir('/content/drive/My Drive/Colab Notebooks/Utilization Management/Data')

Mounted at /content/drive/

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Data

In [3]:
dlmdata = pd.read_csv('FirstExtractEverything1.csv', encoding= 'unicode_escape')

# Overview

In [4]:
dlmdata.head()

,Designated Dept,Designated Workstation,Test Name,Result Name,Protocol ID,Order Number,Order Clinic Code,Order Clinic Patient Type,Order Doctor Code,Patient Code,...,Canceled If @9,Cancellation Reason,Cancelled Date Time,Collection Date Time,Ordered Date Time,Receiving Date Time,Resulted Date Time,Verify Date Time,Result Code,Test Code
0,CHEMISTRY,URINALYSIS AUWI,Urinalysis,Unidentified Crystals,09-I-0102,R9183098,5NW,Inpatient,ALHMA,3684,...,-nul-,NaN,NaN,3/18/2022 9:38,3/18/2022 8:46,3/18/2022 9:45,3/18/2022 8:47,3/18/2022 8:47,IDCR2,UA6
1,CHEMISTRY,URINALYSIS AUWI,Urinalysis,Squamous Epithelial,15-C-0087,S1165215,OP3,Outpatient,DOLRE,8214,...,Cancelled,NaN,NaN,5/16/2022 8:32,5/16/2022 8:28,5/16/2022 8:39,5/16/2022 9:09,5/16/2022 9:16,SQAM2,UA6
2,CHEMISTRY,URINALYSIS AUWI,Urinalysis,Urobilinogen,09-I-0030,S0287564,OP8,Outpatient,0WABE,1656,...,-nul-,NaN,NaN,4/28/2022 11:04,4/28/2022 10:10,4/28/2022 11:10,4/28/2022 11:16,4/28/2022 11:16,UROB2,UA6
3,CHEMISTRY,ABBOTT CI8200,Acute Care Panel,eGFR (African-American),04-C-0165,R9157804,RADON,Outpatient,WILM2,4780,...,-nul-,NaN,NaN,3/15/2022 11:21,3/15/2022 11:13,3/15/2022 11:53,3/15/2022 12:31,3/15/2022 12:31,GFRA6,ACUT9
4,CHEMISTRY,ABBOTT CI8200,Acute Care Panel,eGFR (African-American),20-CC-0113,R9150492,OP8,Outpatient,SUFAN,3681,...,-nul-,NaN,NaN,3/15/2022 8:14,3/15/2022 0:01,3/15/2022 8:31,3/15/2022 9:13,3/15/2022 9:13,GFRA6,ACUT9

Doctor and Patient Codes can be decoded using codebook saved in Excel, which I will give to Roa.

In [5]:
dlmdata.isna().sum()

Designated Dept                    0
Designated Workstation             0
Test Name                          0
Result Name                        0
Protocol ID                     4460
Order Number                       0
Order Clinic Code                  0
Order Clinic Patient Type          4
Order Doctor Code                  0
Patient Code                       0
Result Text                        4
Modified Result                    0
New Result Text                    4
Canned Result Message Code         0
Result Cancelled                   0
Result Message                     0
Canceled If @9                     0
Cancellation Reason           721036
Cancelled Date Time           685177
Collection Date Time               0
Ordered Date Time                  0
Receiving Date Time            35956
Resulted Date Time              2741
Verify Date Time                5574
Result Code                        0
Test Code                          0
dtype: int64

In [6]:
print('There are ' +str(dlmdata.shape[0]) + ' data entries for the 3 month extraction period.')

There are 721036 data entries for the 3 month extraction period.

In [7]:
dlmdata.columns

Index(['Designated Dept', 'Designated Workstation', 'Test Name', 'Result Name',
       'Protocol ID', 'Order Number', 'Order Clinic Code',
       'Order Clinic Patient Type', 'Order Doctor Code', 'Patient Code',
       'Result Text', 'Modified Result', 'New Result Text',
       'Canned Result Message Code', 'Result Cancelled', 'Result Message',
       'Canceled If @9', 'Cancellation Reason', 'Cancelled Date Time',
       'Collection Date Time', 'Ordered Date Time', 'Receiving Date Time',
       'Resulted Date Time', 'Verify Date Time', 'Result Code', 'Test Code'],
      dtype='object')

In [8]:
dlmdata = dlmdata[['Designated Dept', 'Designated Workstation', 'Test Name', 'Result Name',
       'Protocol ID', 'Order Number', 'Order Clinic Code',
       'Order Clinic Patient Type', 'Order Doctor Code', 'Patient Code',
       'Result Text', 'Modified Result', 'New Result Text',
       'Canned Result Message Code', 'Result Cancelled', 'Result Message',
       'Canceled If @9', 'Cancellation Reason', 'Cancelled Date Time',
       'Collection Date Time', 'Ordered Date Time', 'Receiving Date Time',
       'Resulted Date Time', 'Verify Date Time']]

Explore and clean the data column-by-column:

#Designated Dept and Workstation

In [9]:
dlmdata['Designated Dept'].unique()

array(['CHEMISTRY', 'MAYO LABORATORY'], dtype=object)

Limit the data to DLM Chemistry

In [10]:
dlmdata0 = dlmdata[dlmdata['Designated Dept']=='CHEMISTRY']
dlmdata0 = dlmdata0.iloc[:,1:]

In [11]:
print('There are ' + str(dlmdata0.shape[0]) + ' data entries from DLM Chemistry')

There are 680703 data entries from DLM Chemistry

In [12]:
dlmdata0['Designated Workstation'].unique()

array(['URINALYSIS AUWI', 'ABBOTT CI8200', 'BLOOD GAS NOVA', 'UA',
       'DIASORIN LIAISON', 'LIPOPROTEIN PROFILE', 'IMMULITE 2000',
       'POINT OF CARE- DLM', 'COBAS-CE', 'PEP, IFE, & CRYO', 'OPTILITE',
       'MASS SPEC ', 'OSMO A2O', 'DIMENSION XPAND', 'ICA & PH(FLUID)',
       'HPLC', 'AML SEND OUTS', 'MISCELL. CHEM.', 'PREG,OSMO,&ETC.',
       'SC MANUAL TESTS', 'URINE LAB(MIRA)'], dtype=object)

The Chemistry department still contains sendouts, as well as point of care and some workstations I don't recognise. I'll explore which tests fall to these workstations.

In [13]:
dlmdata0[dlmdata0['Designated Workstation']=='POINT OF CARE- DLM']['Test Name'].unique()

array(['Glucose, Capillary (CC), POCT'], dtype=object)

In [14]:
dlmdata0[dlmdata0['Designated Workstation']=='AML SEND OUTS']['Test Name'].unique()

array(['Xylose, Blood, 2 hr post', 'Amikacin, Post ', 'Amikacin, Random',
       'Methotrexate Level, Serum ', 'Xylose Absorption, Urine (5 hr)',
       'Amikacin, Pre'], dtype=object)

In [15]:
dlmdata0[dlmdata0['Designated Workstation']=='MISCELL. CHEM.']['Test Name'].unique()

array(['Other Chemistry Test'], dtype=object)

In [16]:
dlmdata0[dlmdata0['Designated Workstation']=='SC MANUAL TESTS']['Test Name'].unique()

array(['RPR Syphilis Sero'], dtype=object)

In [17]:
dlmdata0[dlmdata0['Designated Workstation']=='BLOOD GAS NOVA']['Test Name'].unique()

array(['Chem 2, Whole Blood, Venous', 'Blood Gases, Venous',
       'Creatinine, Whole Blood, Venous', 'Ionized Calcium, WB Venous',
       'Ionized Magnesium, Venous', 'Blood Gases, Arterial',
       'Chem 2, Whole Blood, Arterial', 'Cooximeter Panel, Arterial',
       'Methemoglobin., Venous', 'L-Lactate, Venous',
       'Hematocrit, Venous', 'Potassium, Venous',
       'Carboxyhemoglobin., Venous', 'Hematocrit, Arterial',
       'Methemoglobin., Art.irial', 'Ionized Magnesium, Arterial',
       'Cooximeter Panel, Venous', 'L-Lactate, Arterial'], dtype=object)

In [18]:
dlmdata0[dlmdata0['Designated Workstation']=='ICA & PH(FLUID)']['Test Name'].unique()

array(['HIV-1/2 Rapid Antibody Screen', 'Ketones, Serum', 'pH, Other',
       'HIV Rapid Antibody Screen(OMS)'], dtype=object)

I explored Test Name, Result Name, Result Text and Result Message for 'MISCELL. CHEM.' It seems this is a dummy test for when tests are sent to Mayo as there is no data in any of these columns.
I'll exclude all three of these workstations as they are not relevant to the current analysis. RPR is now sent out but it should not have been a chemistry test in any case. I'll exclude POC, blood gases and fluid pH because these parameters can change rapidly in acute conditions and with treatment, so repeat testing is valid. HIV screening also falls under ICA & PH, but repeat testing is also sometimes valid and this is also not a true chemistry test.

In [19]:
dlmdata1 = dlmdata0[(dlmdata0['Designated Workstation'] != 'BLOOD GAS NOVA') & (dlmdata0['Designated Workstation'] != 'POINT OF CARE- DLM') & (dlmdata0['Designated Workstation'] != 'AML SEND OUTS') & 
                    (dlmdata0['Designated Workstation'] != 'MISCELL. CHEM.') & (dlmdata0['Designated Workstation'] != 'SC MANUAL TESTS') & (dlmdata0['Designated Workstation'] != 'ICA & PH(FLUID)')]

In [20]:
print('There are now ' + str(dlmdata1.shape[0]) + ' data entries.')

There are now 668807 data entries.

#Test Name & Result Name

Now let's check how many unique orderables and reportables we have in our data set.

In [116]:
print('There are '+ str(dlmdata1['Test Name'].nunique()) + ' unique orderable tests and '+ str(dlmdata1['Result Name'].nunique()) + ' unique reportable results.')

There are 236 unique orderable tests and 701 unique reportable results.

I want to exclude tests that are expected to have short repeat intervals, such as serial testing and emergency testing (I've already removed blood gases). I also want to exclude calculated results. I'll have a look at the orderable tests first.

In [117]:
dlmdata1['Test Name'].unique()

array(['Urinalysis', 'Acute Care Panel', 'Mineral Panel',
       'Pregnancy, Urine', 'Hepatic Panel', 'Creatinine, Timed Urine',
       'Free T3', 'Vitamin D, 1,25-Dihydroxy',
       'Vitamin D,  25-Hydroxy Total', 'Uric Acid', 'Lipoprotein Profile',
       'Growth Hormone', 'Lactate Dehydrogenase', 'Lipid Panel',
       'Creatine Kinase', 'Immunoglobulins, Quantitative',
       'C-Peptide Serial 01-08', 'Serum Folate',
       'Immunofixation Electrophoresis, Serum',
       'Protein Creatinine Ratio, Urine',
       'Electrophoresis, Protein, Serum ', 'Troponin I',
       'CRP,High Sensitivity, Comprehensive',
       'Drug Abuse Screen, Qualitative, Urine', 'Iron and Transferrin  ',
       'Magnesium, Random Urine', 'Estradiol, Serum',
       'Pro Brain Natriuretic Peptide', 'Rheumatoid Factor', 'Lipase',
       'Protein, Total', 'Ferritin', 'Albumin/Creatinine Ratio, Urine',
       'Free Fatty Acid Serial 01-08', 'Anti-Varicella-Zoster Virus IgG',
       'Cystatin C', 'Insulin Serial 01-08',
       'Anti-S SARS-CoV-2 Antibodies', 'Immunoglobulin Free Light Chains',
       'Thyroid Stimulating Hormone ',
       'Cortisol & Cortisone, Free, 24 hr Urine',
       'Testosterone Total and Free by Calculation', 'Osmolality, Serum',
       'Triglycerides', 'Angiotensin Conv.Enzyme', 'Cyclosporin Level',
       'Thyroglobulin Panel', 'Amylase', 'Creatinine Clearance',
       'Apolipoprotein Panel', 'CA125 (Cancer Antigen 125)',
       'Free Fatty Acids,Serum', 'Alanine Aminotransferase',
       'Triiodothyronine', 'Toxoplasma Ab IgG', 'ACTH Serial 01-08',
       'Gamma Glutamyl Transferase', 'Anti-EBV Antibody Panel',
       'Oligo. Banding CSF and Serum', 'Calcium, Timed Urine',
       'Beta-2-Microglob., Serum', 'C3/C4',
       'Anti-N SARS-CoV-2 Antibodies',
       'Phosphorous, Inorganic, Timed Urine', 'IgG Index, CSF',
       'Osteocalcin', 'Aldosterone, Serum', 'Aspartate Aminotransferase',
       'Creatinine ', 'Follicle Stimulating Hormone', 'Calcium',
       'Cortisol, Serum', 'Human Chorionic Gonadotropin, Preg',
       'Testosterone, Total', 'IGF-1 (Somatomedin C)',
       'Prostatic Specific Antigen', 'IgE', 'Reagent Strip, Urine',
       'Haptoglobin', 'Electrolytes', 'Phosphorus, Random Urine',
       'Anti-Thyroid Panel', 'Thyroxine, Free', 'Vitamin B12',
       'Anti-Cytomegalovirus IgG,IgM Antibody', 'Ceruloplasmin',
       'Aldolase', 'Free Fatty Acid Serial 26-40', 'Bilirubin, Total',
       'Phosphorus, Inorganic', 'Insulin', 'Protein, CSF', 'Prolactin',
       'Androstenedione, Serum', 'Creatinine, Random Urine', 'Albumin',
       'ACTH, Plasma', 'DHEA Sulfate', 'Specific Gravity, Urine.',
       'TBG(Thyroxin Bind. Glob)', 'Free Fatty Acid Serial 09-15',
       'Rubella Ab,IgG', 'Alpha-fetoprotein (AFP)', 'Prealbumin',
       'Growth Hormone 26-40', 'Digoxin Level', 'Albumin, Timed Urine',
       'Luteinizing Hormone (LH)', 'Alpha-1-Antitrypsin',
       'Progesterone, Serum', 'PTH, Intact', 'Protein, Timed Urine',
       'Thyroxine', 'Sirolimus (Rapamycin)', 'Glucose', 'CEA ',
       'Sodium, Timed Urine', 'CK-MB Immunoassay', 'Lactate-L, Plasma',
       'Sodium, Random Urine', 'Potassium', 'Osmolality, Urine',
       'Glucose Tolerance Test 3hr', 'Homocysteine,Total,Plasma',
       'PTH Serial 09-15', 'Lactate Serial, Plasma 26-40',
       'Cortisol Serial 01-08', 'HDL Cholesterol ', 'CA 15-3 (Cancer Ag)',
       'Insulin Serial 16-25', 'Growth Hormone 1-8',
       'Protein, Total, Other', 'C-Peptide, Serum',
       'Calcium, Random Urine', 'Dehydroepiandrosterone, Serum',
       'Cortisol, Serum, Diurnal, PM', 'Beta-2-Microglob., Urine',
       'Magnesium, Timed Urine', 'Glucose Serial 09-15',
       'Sex Hormone Binding Globulin', 'Sodium',
       'Uric Acid, Random Urine', 'Alkaline Phosphatase',
       'Vancomycin Level, Pre', 'Anti-Rubeola IGG',
       'Glucose, Timed Urine', 'Cortisol & Cortisone, Free, Random Urine',
       'Glucose Serial 01-08 ', '17-OH Progesterone, Serum ',
       'Prolactin serial 01-08', 'C-Peptide Serial 09-15', 'Glucose, CSF',
       'Potassium, Random Urine', 'Electrolytes, Random Urine',
       'PTH Serial 26-40', 'Creatinine, Other',
       '3-Methoxytyramine, Plasma', 'Triglyceride Serial 01-08',
       'Lactate Serial, Plasma 01-08', 'Total CO2 ', 'EBVCA-IgG',
       'Insulin Serial 09-15', 'Glucose Serial 16-25',
       'Tacrolimus(FK506)', 'Potassium, Timed Urine', 'PTH Serial 01-08',
       'Vancomycin Level, Random', 'Cortisol Serial 16-25',
       'Bilirubin, Direct', 'ACTH Serial 09-15',
       'Lactate Serial, Plasma 16-25', 'Growth Hormone 16-25',
       'Uric Acid, Timed Urine', 'Aldosterone Serial 01-08', 'Chloride',
       'CA 19-9 (Cancer Ag)', 'Prolactin Serial 16-25', 'Ammonia Level',
       'Urea Nitrogen', 'Cortisol Serial 09-15', 'L-Lactate, CSF',
       'Amylase, Other', 'Cortisol Serial 01-03', 'Cholesterol, Total',
       'Glucose Serial 26-40 ', 'Triglycerides, Other', 'Busulfan Level',
       'Urea Nitrogen, Timed Urine', 'Cortisol, Serum, Diurnal, AM',
       'Glucose, Plasma', 'Testosterone Total, Serum, Mass Spec',
       'Magnesium', 'Valproic Acid Level', 'pH, Urine.',
       'Urea Nitrogen, Random Urine', 'Lithium Level ',
       'Insulin Serial 26-40', 'ACTH Serial 16-25',
       'Lactate Dehydrogenase, Other', 'Glucose, Random Urine',
       'PTH Serial 16-25', 'Carbamazepine Level', 'LH Serial 1-8',
       'Vancomycin Level, Post', 'Immunofix(IFE), Random Ur.',
       'Beta-2-Microglobin,  Time Urine', 'Electrolytes, Timed Urine',
       'Free Fatty Acid Serial 16-25', 'Crystal ID,Synovial Fluid',
       'FSH Serial 1-8', 'Tobramycin Level, Random',
       '11-Deoxycortisol, Serum', 'Phenytoin Level', 'Steroids Profile',
       'Oxycodone Level, Urine', 'Lactate Serial, Plasma 09-15',
       'Prolactin Serial 09-15', 'Albumin, Other',
       'Chloride, Timed Urine', 'Progesterone, Serum, Mass Spec',
       'Chloride, Random Urine', 'Cortisol, Serum, Mass Spec',
       'Cortisone,  Serum, Mass Spec', 'Glucose, Other', 'Albumin, CSF',
       'Growth Hormone 9-15', 'IgG, CSF', 'Ketones, Urine',
       'Fentanyl Level, Urine', 'Gentamicin Level, Random',
       'Buprenorphine Level, Urine', 'Hemoglobin, Urine',
       'Corticosterone, Serum, Mass Spec',
       'T3 Free & T4 Free, Mass Spectrometry', 'Creatinine, Urine',
       'Tobramycin Level, Post'], dtype=object)

In [118]:
serials = dlmdata1['Test Name'][dlmdata1['Test Name'].str.contains('Serial')]

In [119]:
glucose = dlmdata1['Test Name'][dlmdata1['Test Name'].str.contains('Glucose')]

In [120]:
#other tests identified manually
GHSerial = dlmdata1['Test Name'][dlmdata1['Test Name'].str.contains('Growth Hormone ')]
moreserials = dlmdata1['Test Name'][dlmdata1['Test Name'].str.contains('serial')]

I'll remove all the tests identified above as serial or emergnecy testing that have no minimum repeat interval.

In [121]:
dlmdata2 = dlmdata1[~dlmdata1['Test Name'].isin(serials)]
dlmdata2 = dlmdata2[~dlmdata2['Test Name'].isin(glucose)]
dlmdata2 = dlmdata2[~dlmdata2['Test Name'].isin(GHSerial)]
dlmdata2 = dlmdata2[~dlmdata2['Test Name'].isin(moreserials)]

In [122]:
dlmdata2['Test Name'].unique()

array(['Urinalysis', 'Acute Care Panel', 'Mineral Panel',
       'Pregnancy, Urine', 'Hepatic Panel', 'Creatinine, Timed Urine',
       'Free T3', 'Vitamin D, 1,25-Dihydroxy',
       'Vitamin D,  25-Hydroxy Total', 'Uric Acid', 'Lipoprotein Profile',
       'Growth Hormone', 'Lactate Dehydrogenase', 'Lipid Panel',
       'Creatine Kinase', 'Immunoglobulins, Quantitative', 'Serum Folate',
       'Immunofixation Electrophoresis, Serum',
       'Protein Creatinine Ratio, Urine',
       'Electrophoresis, Protein, Serum ', 'Troponin I',
       'CRP,High Sensitivity, Comprehensive',
       'Drug Abuse Screen, Qualitative, Urine', 'Iron and Transferrin  ',
       'Magnesium, Random Urine', 'Estradiol, Serum',
       'Pro Brain Natriuretic Peptide', 'Rheumatoid Factor', 'Lipase',
       'Protein, Total', 'Ferritin', 'Albumin/Creatinine Ratio, Urine',
       'Anti-Varicella-Zoster Virus IgG', 'Cystatin C',
       'Anti-S SARS-CoV-2 Antibodies', 'Immunoglobulin Free Light Chains',
       'Thyroid Stimulating Hormone ',
       'Cortisol & Cortisone, Free, 24 hr Urine',
       'Testosterone Total and Free by Calculation', 'Osmolality, Serum',
       'Triglycerides', 'Angiotensin Conv.Enzyme', 'Cyclosporin Level',
       'Thyroglobulin Panel', 'Amylase', 'Creatinine Clearance',
       'Apolipoprotein Panel', 'CA125 (Cancer Antigen 125)',
       'Free Fatty Acids,Serum', 'Alanine Aminotransferase',
       'Triiodothyronine', 'Toxoplasma Ab IgG',
       'Gamma Glutamyl Transferase', 'Anti-EBV Antibody Panel',
       'Oligo. Banding CSF and Serum', 'Calcium, Timed Urine',
       'Beta-2-Microglob., Serum', 'C3/C4',
       'Anti-N SARS-CoV-2 Antibodies',
       'Phosphorous, Inorganic, Timed Urine', 'IgG Index, CSF',
       'Osteocalcin', 'Aldosterone, Serum', 'Aspartate Aminotransferase',
       'Creatinine ', 'Follicle Stimulating Hormone', 'Calcium',
       'Cortisol, Serum', 'Human Chorionic Gonadotropin, Preg',
       'Testosterone, Total', 'IGF-1 (Somatomedin C)',
       'Prostatic Specific Antigen', 'IgE', 'Reagent Strip, Urine',
       'Haptoglobin', 'Electrolytes', 'Phosphorus, Random Urine',
       'Anti-Thyroid Panel', 'Thyroxine, Free', 'Vitamin B12',
       'Anti-Cytomegalovirus IgG,IgM Antibody', 'Ceruloplasmin',
       'Aldolase', 'Bilirubin, Total', 'Phosphorus, Inorganic', 'Insulin',
       'Protein, CSF', 'Prolactin', 'Androstenedione, Serum',
       'Creatinine, Random Urine', 'Albumin', 'ACTH, Plasma',
       'DHEA Sulfate', 'Specific Gravity, Urine.',
       'TBG(Thyroxin Bind. Glob)', 'Rubella Ab,IgG',
       'Alpha-fetoprotein (AFP)', 'Prealbumin', 'Digoxin Level',
       'Albumin, Timed Urine', 'Luteinizing Hormone (LH)',
       'Alpha-1-Antitrypsin', 'Progesterone, Serum', 'PTH, Intact',
       'Protein, Timed Urine', 'Thyroxine', 'Sirolimus (Rapamycin)',
       'CEA ', 'Sodium, Timed Urine', 'CK-MB Immunoassay',
       'Lactate-L, Plasma', 'Sodium, Random Urine', 'Potassium',
       'Osmolality, Urine', 'Homocysteine,Total,Plasma',
       'HDL Cholesterol ', 'CA 15-3 (Cancer Ag)', 'Protein, Total, Other',
       'C-Peptide, Serum', 'Calcium, Random Urine',
       'Dehydroepiandrosterone, Serum', 'Cortisol, Serum, Diurnal, PM',
       'Beta-2-Microglob., Urine', 'Magnesium, Timed Urine',
       'Sex Hormone Binding Globulin', 'Sodium',
       'Uric Acid, Random Urine', 'Alkaline Phosphatase',
       'Vancomycin Level, Pre', 'Anti-Rubeola IGG',
       'Cortisol & Cortisone, Free, Random Urine',
       '17-OH Progesterone, Serum ', 'Potassium, Random Urine',
       'Electrolytes, Random Urine', 'Creatinine, Other',
       '3-Methoxytyramine, Plasma', 'Total CO2 ', 'EBVCA-IgG',
       'Tacrolimus(FK506)', 'Potassium, Timed Urine',
       'Vancomycin Level, Random', 'Bilirubin, Direct',
       'Uric Acid, Timed Urine', 'Chloride', 'CA 19-9 (Cancer Ag)',
       'Ammonia Level', 'Urea Nitrogen', 'L-Lactate, CSF',
       'Amylase, Other', 'Cholesterol, Total', 'Triglycerides, Other',
       'Busulfan Level', 'Urea Nitrogen, Timed Urine',
       'Cortisol, Serum, Diurnal, AM',
       'Testosterone Total, Serum, Mass Spec', 'Magnesium',
       'Valproic Acid Level', 'pH, Urine.', 'Urea Nitrogen, Random Urine',
       'Lithium Level ', 'Lactate Dehydrogenase, Other',
       'Carbamazepine Level', 'Vancomycin Level, Post',
       'Immunofix(IFE), Random Ur.', 'Beta-2-Microglobin,  Time Urine',
       'Electrolytes, Timed Urine', 'Crystal ID,Synovial Fluid',
       'Tobramycin Level, Random', '11-Deoxycortisol, Serum',
       'Phenytoin Level', 'Steroids Profile', 'Oxycodone Level, Urine',
       'Albumin, Other', 'Chloride, Timed Urine',
       'Progesterone, Serum, Mass Spec', 'Chloride, Random Urine',
       'Cortisol, Serum, Mass Spec', 'Cortisone,  Serum, Mass Spec',
       'Albumin, CSF', 'IgG, CSF', 'Ketones, Urine',
       'Fentanyl Level, Urine', 'Gentamicin Level, Random',
       'Buprenorphine Level, Urine', 'Hemoglobin, Urine',
       'Corticosterone, Serum, Mass Spec',
       'T3 Free & T4 Free, Mass Spectrometry', 'Creatinine, Urine',
       'Tobramycin Level, Post'], dtype=object)

In [123]:
resultnames = dlmdata2['Result Name'].unique()

In [124]:
searchterms = ['egfr','calculat', 'ratio', 'index', 'excretion', 'clearance', 'gap', 'quotient']
calculated = [r for r in resultnames if any(term in r.lower() for term in searchterms)]
print(calculated)

['eGFR (African-American)', 'eGFR (Non-African-American)', 'Anion Gap', 'Protein Creatinine Ratio, Urine', 'Secal Calculation', 'Electrophoresis Calculation', 'Albumin/Creatinine Ratio, Urine', '%Saturation', 'eGFR Cystatin C', 'LDL Cholesterol-Calculated', 'Corrected Creatinine Clearance', 'Collection Duration', 'Phosphorus Excretion', 'ALB Quotient', 'Creatinine Excretion', 'Free Kappa/Free Lambda Ratio', 'Sodium Excretion', 'Protein Excretion', 'Calcium Excretion', 'Magnesium  Excretion', 'Cortisol, Free/Cr Ratio, Random Ur', 'Collection Duration, 24h U', 'IgG index, CSF', 'Albumin Excretion', 'Potassium, Excretion', 'Uric Acid Excretion', 'Creatinine Clearance', 'Urea Nitrogen Excretion', 'Cortisone,Free/Cr Ratio, Random Ur', 'Chloride, Excretion']

In [125]:
searchterms = ['height', 'weight','volume', 'area']
nonlab = [r for r in resultnames if any(term in r.lower() for term in searchterms)]
print(nonlab)

['Urine Volume, 24 hr, U', 'Volume', 'Height', 'Body Surface Area', 'Weight']

In [126]:
#other discovered manually
searchterms = ['sample','pr comm.', 'ketones', 'color', 'serum immunofix electro']
other = [r for r in resultnames if any(term in r.lower() for term in searchterms)]
print(other)

['Pr comm.', 'Ketones', 'Color', 'Serum Immunofix Electro', 'Busulfan Level, sample 6', 'Collection Time sample 3', 'Collection Time sample 4', 'Collection Date sample 2', 'Busulfan Level, sample 4', 'Collection Time sample 2', 'Collection Date sample 1', 'Busulfan Level, sample 1', 'Collection Date sample 6', 'Collection Time sample 6', 'Collection Date sample 4', 'Busulfan Level, sample 3', 'Collection Time sample 5', 'Ketones, Urine', 'Collection Time sample 1', 'Collection Date sample 5', 'Busulfan Level, sample 2', 'Busulfan Level, sample 5', 'Collection Date sample 3']

In [127]:
dlmdata2[dlmdata2['Test Name'] == 'Lipoprotein Profile']['Result Name'].unique()

array(['Triglyceride ', 'Large LDL Particle Number',
       'Small HDL Particle Number', 'Large Medium HDL Particle Number',
       'VLDLTriglyceride', 'Lipoprotein Insulin Resistance Score',
       ' Cholesterol', 'LDL Particle Number', 'VLDL Size', 'LDL Size',
       'Small LDL Particle Number', 'HDL Particle Number',
       'VLDL and LDL Particle Number',
       'Large Medium VLDL Particle Number', 'Medium HDL Particle Number',
       'Small VLDL Particle Number', 'VLDL Particle Number',
       'IDL Particle Number', 'LDL Cholesterol',
       'Large VLDL Particle Number', 'HDL Size',
       'Medium VLDL Particle Number', 'Large HDL Particle Number',
       'HDL Cholesterol  '], dtype=object)

In [128]:
lipoprofile = ['Triglyceride ', 'Large LDL Particle Number',
       'Small HDL Particle Number', 'Large Medium HDL Particle Number',
       'VLDLTriglyceride', 'Lipoprotein Insulin Resistance Score',
       ' Cholesterol', 'VLDL Size', 'LDL Size',
       'Small LDL Particle Number', 'HDL Particle Number',
       'VLDL and LDL Particle Number',
       'Large Medium VLDL Particle Number', 'Medium HDL Particle Number',
       'Small VLDL Particle Number', 'VLDL Particle Number',
       'IDL Particle Number', 'LDL Cholesterol',
       'Large VLDL Particle Number', 'HDL Size',
       'Medium VLDL Particle Number', 'Large HDL Particle Number',
       'HDL Cholesterol  ']

I'll remove all the results identified above as emergency or calculated parameters. I'll also exclude all but the 'LDL Particle Number' from the lipoprotein profile as many of these are not FDA-cleared and will produce null results.

In [129]:
dlmdata3 = dlmdata2[~dlmdata2['Result Name'].isin(calculated)]
dlmdata3 = dlmdata3[~dlmdata3['Result Name'].isin(nonlab)]
dlmdata3 = dlmdata3[~dlmdata3['Result Name'].isin(other)]
dlmdata3 = dlmdata3[~dlmdata3['Result Name'].isin(lipoprofile)]

In [130]:
dlmdata3['Result Name'].unique()

array(['Unidentified Crystals', 'Squamous Epithelial', 'Urobilinogen',
       'Transitional Epithelial', 'Phosphorus, Inorganic', 'Potassium',
       'Bacteria', 'Renal Cell Casts', 'Bilirubin, Total', 'Bilirubin',
       'Magnesium', 'pH, Urine.', 'Alanine Aminotransferase',
       'Aspartate Aminotransferase', 'Creatinine, Urine', 'WBC, Urine',
       'Albumin', 'Mucus', 'Free T3', 'Crystal Check AUWi',
       'Fat Droplets', 'Vitamin D, 1,25-Dihydroxy',
       'Vitamin D,  25-Hydroxy Total', 'Waxy Casts', 'Clarity',
       'Uric Acid', 'Glucose, Urine.', 'Sodium', 'WBC Casts',
       'Calcium Phosphate Crystals', 'Growth Hormone',
       'Lactate Dehydrogenase', 'Granular Casts', 'Cholesterol, Total',
       'Creatine Kinase', 'Alkaline Phosphatase', 'Chloride', 'Calcium',
       'Nitrite', 'Trichomonas', 'Cystine Crystals', 'HDL Cholesterol ',
       'Fatty Casts', 'Urea Nitrogen', 'IgM ', 'Path Cast Check AUWi',
       'Total CO2 ', 'Leucine Crystals', 'Serum Folate', 'Glucose',
       'M-spike', 'Calcium Oxalate Crystals', 'RBC Casts', 'Troponin I',
       'CRP,High Sensitivity, Comprehensive', 'Creatinine',
       'Cocaine Metabolites,', 'Small Round Cells Check AUWi',
       'Hyphenated Yeast', 'Transferrin', 'Magnesium, Random Urine',
       'Estradiol, Serum', 'Pro Brain Natriuretic Peptide',
       'Rheumatoid Factor', 'Manual Urine Microscopic Exam',
       'Calcium Carbonate Crystals', 'Uric Acid Crystals',
       'Protein, Urine.', 'Bilirubin, Direct', 'Hyaline Casts', 'Lipase',
       'Protein, Total', 'Ferritin', 'IgG ', 'Tyrosine Crystals',
       'Anti-Varicella-Zoster Virus IgG', 'RBC, Urine',
       'Hemoglobin, Urine', 'Yeast Check AUWi', 'Leukocyte Esterase',
       'Renal Epithelial', 'Anti-S SARS-CoV-2 Antibodies',
       'Triglycerides', 'Oval Fat Bodies', 'Free Kappa Light Chain',
       'Thyroid Stimulating Hormone ', 'Broad Casts',
       'Specific Gravity, Urine.', 'Budding Yeast', 'Testosterone, Total',
       'LDL Particle Number', 'Osmolality, Serum',
       'Testosterone, Free (calc)', 'Angiotensin Conv.Enzyme',
       'Cyclosporin Level', 'Anti-Thyroglobulin', 'Amylase',
       'Apolipoprotein B', 'IgA', 'CA125 (Cancer Antigen 125)',
       'Free Fatty Acids,Serum', 'Triiodothyronine',
       'Triple Phosphate Crystals', 'Cannabinoids (THC)',
       'Toxoplasma Ab IgG', 'Gamma Glutamyl Transferase', 'EBVCA-IgG',
       'IgG, CSF', 'Protein, Urine', 'EBNA', 'Beta-2-Microglob.,Serum',
       'C3 Complement', 'Anti-N SARS-CoV-2 Antibodies', 'Osteocalcin',
       'Aldosterone, Serum', 'Alpha 1 ', 'Creatinine, Random Urine',
       'Follicle Stimulating Hormone', 'Cortisol, Serum',
       'Human Chorionic Gonadotropin, Preg', 'IGF-1 (Somatomedin C)',
       'Prostatic Specific Antigen', 'Sex Hormone Binding Globulin',
       'IgE', 'Haptoglobin', 'C4 Complement', 'Phosphorus, Random Urine',
       'Thyroid PeroxidaseAB', 'Thyroxine, Free', 'Gamma  ',
       'Vitamin B12', 'CMV Ab IgG', 'Ceruloplasmin', 'Aldolase',
       'Pregnancy, Urine', 'Insulin', 'Free Lambda Light Chain',
       'Protein, CSF', 'Prolactin', 'Androstenedione, Serum', 'Alpha 2  ',
       'ACTH, Plasma', 'DHEA Sulfate', 'Cystatin C', 'Beta 2',
       'Methadone.', 'Iron', 'Beta 1', 'Cortisol, Free, 24h Ur',
       'Benzodiazepine', 'EBVCA-IgM', 'TBG(Thyroxin Bind. Glob)',
       'Albumin, Random Urine', 'Rubella Ab,IgG',
       'Alpha-fetoprotein (AFP)', 'Prealbumin', 'Thyroglobulin',
       'Digoxin Level', 'Amphetamines', 'Luteinizing Hormone (LH)',
       'Alpha-1-Antitrypsin', 'Progesterone, Serum', 'PTH, Intact',
       'Thyroxine', 'Sirolimus (Rapamycin)', 'Apolipoprotein A-1', 'CEA ',
       'Albumin, Serum Optilite', 'CK-MB Immunoassay',
       'Lactate-L, Plasma', 'Sodium, Random Urine', 'Osmolality, Urine',
       'Calcium, Urine', 'Homocysteine,Total,Plasma', 'Opiates',
       'CMV Ab IgM', 'CA 15-3 (Cancer Ag)', 'Oligoclonal Bands, CSF',
       'Protein, Total, Other', 'IG G, Serum Optilite',
       'C-Peptide, Serum', 'Calcium, Random Urine',
       'Dehydroepiandrosterone, Serum', 'Cortisol, Serum 12:00am',
       'Beta-2-Microglob.,Urine', 'Albumin, CSF',
       'Uric Acid, Random Urine', 'Vancomycin Level, Pre',
       'Anti-Rubeola IGG', 'Phosphorus, Inorganic, Urine',
       'Sodium, Urine', '17-OH Progesterone, Serum ',
       'Potassium, Random Urine', 'Creatinine, Other',
       '3-Methoxytyramine, Plasma', 'Cortisol, Free, Urine',
       'Tacrolimus(FK506)', 'Vancomycin Level, Random',
       'Chloride, Random Urine', 'Cortisone, Free, 24h Ur',
       'CA 19-9 (Cancer Ag)', 'Ammonia Level', 'L-Lactate, CSF',
       'Magnesium, Urine', 'Amylase, Other', 'Triglycerides, Other',
       'Cortisone, Free, Urine', 'Cortisol, Serum, 8:00am',
       'Albumin, Urine', 'Testosterone Total, Serum, Mass Spec',
       'Cortisol, Serum 11:30pm', 'Valproic Acid Level',
       'Potassium, Urine', 'Urea Nitrogen, Random Urine',
       'Lithium Level ', 'Cortisol, Serum, 7:30am',
       'Lactate Dehydrogenase, Other', 'Uric Acid, Urine',
       'Carbamazepine Level', 'Urea Nitrogen, Urine',
       'Vancomycin Level, Post', 'Crystal ID,Synovial Fluid',
       'Tobramycin Level, Random', '11-Deoxycortisol, Serum',
       'Phenytoin Level', 'Cortisone,  Serum, Mass Spec',
       'Oxycodone Level, Urine', 'Chloride, Urine', 'Albumin, Other',
       'Cortisone, Free, Random Urine', 'Progesterone, Serum, Mass Spec',
       'Cortisol, Free, Random Urine', 'Cortisol, Serum, Mass Spec',
       'Corticosterone, Serum, Mass Spec', 'Beta Globulin',
       'Gamma Globulin', 'Fentanyl Level, Urine',
       'Gentamicin Level, Random', 'Buprenorphine Level, Urine',
       'T4 Free, Mass Spectrometry', 'EBNA-IgG',
       'Immunofix(IFE), Rand.Ur', 'Alpha 2 Globulin',
       'Tobramycin Level, Post', 'Alpha 1 Globulin',
       'T3 Free, Mass Spectrometry'], dtype=object)

In [131]:
print('There are now '+ str(dlmdata3['Test Name'].nunique()) + ' unique orderable tests and '+ str(dlmdata3['Result Name'].nunique()) + ' unique reportable results.')

There are now 187 unique orderable tests and 246 unique reportable results.

#Protocol ID

In [132]:
print('There are ' + str(dlmdata3['Protocol ID'].isna().sum()) + ' tests that do not have a Protocol ID.')

There are 3484 tests that do not have a Protocol ID.

In [133]:
dlmdata3[dlmdata3['Protocol ID'].isna()].head(10)

,Designated Workstation,Test Name,Result Name,Protocol ID,Order Number,Order Clinic Code,Order Clinic Patient Type,Order Doctor Code,Patient Code,Result Text,...,Result Cancelled,Result Message,Canceled If @9,Cancellation Reason,Cancelled Date Time,Collection Date Time,Ordered Date Time,Receiving Date Time,Resulted Date Time,Verify Date Time
283,ABBOTT CI8200,"Protein, Total","Protein, Total",NaN,S0204944,LAB,Outpatient,FLETH,1000,. TCANC14,...,Y,-nul-,-nul-,NaN,4/22/2022 11:43,4/20/2022 16:11,4/20/2022 16:11,4/22/2022 8:38,4/22/2022 11:43,4/22/2022 11:43
673,ABBOTT CI8200,Hepatic Panel,Aspartate Aminotransferase,NaN,R9225294,3NW,Inpatient,FRAKA,8989,16,...,N,-nul-,-nul-,NaN,NaN,3/22/2022 10:41,3/22/2022 10:41,3/22/2022 10:41,3/22/2022 11:16,3/22/2022 11:18
817,ABBOTT CI8200,Iron and Transferrin,Ferritin,NaN,R9089933,LAB,Outpatient,FRAKA,8987,54,...,N,-nul-,-nul-,NaN,NaN,3/8/2022 10:48,3/8/2022 10:48,3/8/2022 10:48,3/8/2022 11:49,3/8/2022 11:50
1156,URINALYSIS AUWI,Urinalysis,Leukocyte Esterase,NaN,Q9205965,3SW-F,Inpatient,FLETH,8990,-nul-,...,N,-nul-,-nul-,NaN,NaN,4/13/2022 12:21,4/13/2022 12:21,4/13/2022 12:21,NaN,NaN
1614,ABBOTT CI8200,Mineral Panel,Albumin,NaN,S0228142,LAB,Outpatient,FLETH,1000,4.5,...,N,-nul-,-nul-,NaN,NaN,4/22/2022 9:30,4/22/2022 9:30,4/22/2022 9:30,4/22/2022 12:03,4/22/2022 12:13
1764,URINALYSIS AUWI,Urinalysis,Hyphenated Yeast,NaN,R9284903,LAB,Outpatient,FRAKA,8992,.,...,Y,-nul-,-nul-,NaN,NaN,3/28/2022 12:49,3/28/2022 12:49,3/28/2022 12:49,3/28/2022 12:49,3/28/2022 12:49
1820,URINALYSIS AUWI,Urinalysis,Transitional Epithelial,NaN,S1055566,LAB,Outpatient,FRAKA,8992,.,...,Y,-nul-,-nul-,NaN,NaN,5/5/2022 11:14,5/5/2022 11:14,5/5/2022 11:14,5/5/2022 11:14,5/5/2022 11:14
1949,ABBOTT CI8200,"Immunoglobulins, Quantitative",IgG,NaN,S0228472,LAB,Outpatient,FLETH,1000,1125,...,N,-nul-,-nul-,NaN,NaN,4/22/2022 11:02,4/22/2022 11:02,4/22/2022 11:02,4/22/2022 11:57,4/22/2022 11:59
2220,ABBOTT CI8200,"Protein, Total","Protein, Total",NaN,R9147957,LAB,Outpatient,CAP,8859,8.3,...,N,-nul-,-nul-,NaN,NaN,3/14/2022 7:12,3/14/2022 7:12,3/14/2022 7:12,3/14/2022 9:25,3/14/2022 9:32
2325,ABBOTT CI8200,Triglycerides,Triglycerides,NaN,S0204623,LAB,Outpatient,FLETH,1000,> 1420,...,N,-nul-,-nul-,NaN,NaN,4/20/2022 14:03,4/22/2022 9:49,4/22/2022 8:50,4/22/2022 10:29,4/22/2022 10:31

They all seem to be ordered by the same doctors and some are from the LAB and are CAP tests. Those with 4-digit Patient MRN numbers were ordered by the lab (MRNs have been coded. Those with 4 digit MRN were coded '1000' - '1003').

In [134]:
dlmdata3[dlmdata3['Protocol ID'].isna()]['Order Doctor Code'].unique()

array(['FLETH', 'FRAKA', 'CAP', 'WESKA', 'GEODA', 'ABATE', 'DIANA',
       'DIMDI'], dtype=object)

In order to keep this notebook anonymous, I checked these doctor codes against a doctor codebook I've saved in Excel. Some of the Order Doctors are lab staff or CAP (FRAKA, FLETH, CAP)

In [135]:
dlmdata4 = dlmdata3.copy()
dlmdata4 = dlmdata3[(dlmdata3['Order Doctor Code'] != 'CAP') & (dlmdata3['Order Doctor Code'] != 'FRAKA') & (dlmdata3['Order Doctor Code'] != 'FLETH')]

In [ ]:
dlmdata4[(dlmdata4['Protocol ID'].isna()) & (dlmdata4['Order Doctor Code'] == 'DIMDI')]

For some tests, there is a Protocol ID in Soft, but it didn't come through with the data. I'll replace those.

In [ ]:
pID = {'R9266112':'14-AA-0181','R9266121': '14-AA-0181', 'R9266122':'14-AA-0181', 'R9266115':'18-C-0135', 'R9266125':'18-C-0135'}
dlmdata4.loc[:,'Protocol ID'] = dlmdata4['Protocol ID'].fillna(dlmdata4['Order Number'].apply(lambda x: pID.get(x)))

In [139]:
dlmdata4[dlmdata4['Protocol ID'].isna()]['Order Clinic Code'].unique()

array(['DONOR', 'CADRE'], dtype=object)

In [ ]:
dlmdata4[dlmdata4['Order Clinic Code'] == 'CADRE']

DONOR codes for DTM DONOR SPECIMENS, and none of these appear in CRIS or have patient names. CADRE appears to code for internal lab tests.
##Check this and if there are any other clinics to exclude.

In [141]:
dlmdata4 = dlmdata4[(dlmdata4['Order Clinic Code'] != 'DONOR') & (dlmdata4['Order Clinic Code'] != 'CADRE')]

In [145]:
print('There are now ' + str(dlmdata4['Protocol ID'].isna().sum()) + ' tests without a Protocol ID, \n and there are ' + str(dlmdata4.shape[0]) + ' total data entries.')

There are now 0 tests without a Protocol ID,
 and there are 571801 total data entries.

#Order Number, Clinic Code, Patient Type & Patient Code

In [147]:
dlmdata4.columns

Index(['Designated Workstation', 'Test Name', 'Result Name', 'Protocol ID',
       'Order Number', 'Order Clinic Code', 'Order Clinic Patient Type',
       'Order Doctor Code', 'Patient Code', 'Result Text', 'Modified Result',
       'New Result Text', 'Canned Result Message Code', 'Result Cancelled',
       'Result Message', 'Canceled If @9', 'Cancellation Reason',
       'Cancelled Date Time', 'Collection Date Time', 'Ordered Date Time',
       'Receiving Date Time', 'Resulted Date Time', 'Verify Date Time'],
      dtype='object')

I'll leave duplicate order numbers for now as some results within an order may not have been reportable and that would serve as a reason for repeat testing. Duplicates will be removed before presenting results.

I noted that some patients had 4 digit MRN's when coding the patients. These were ordered within the LAB and were excluded in the previous section.

In [ ]:
dlmdata4[dlmdata4['Patient Code'] == '1000']

In [149]:
dlmdata4['Order Clinic Code'].unique()

array(['5NW', 'OP3', 'OP8', 'EXT', '3NE', 'OP12', '5SE-S', '3SWS1', 'OP9',
       '5SWDH', 'OP10', '3SE-N', '3SEDH', '1NW', 'RADON', '7SW-N', 'OP11',
       '3NW', '3SW-S', '1H-PE', '1SE', '1H-AL', 'OP4', 'OP7', '1NW-D',
       '7SE', '5SE-N', 'OP5', '1SW', 'NIEHS', '5SW-N', 'OP13', 'OPDEN',
       'OPVEC', 'OPLAB', 'O5NW', 'OPB3M', 'IPSRG', 'O5SE', 'O5SWN',
       'OPBB', 'O3SEN', '1SW-D', 'ADMIS', 'O5NES', '3SE-S', 'OP6', 'OMS',
       'NIA', 'OPREH', '5SW-S', 'O5SWD', 'OPSRG', 'OPRAD', 'OPRCV',
       'IPRCV', '7SW-S', 'O7SWS'], dtype=object)

##Decode these and determine if any should be excluded.

In [148]:
dlmdata4['Order Clinic Patient Type'].unique()

array(['Inpatient', 'Outpatient'], dtype=object)

#Results

In [154]:
dlmdata4[['Result Text', 'Modified Result',
       'New Result Text', 'Canned Result Message Code', 'Result Cancelled',
       'Result Message', 'Canceled If @9', 'Cancellation Reason']]

,Result Text,Modified Result,New Result Text,Canned Result Message Code,Result Cancelled,Result Message,Canceled If @9,Cancellation Reason
0,.,N,.,-nul-,Y,-nul-,-nul-,NaN
1,-nul-,N,-NUL-,@9IMP,N,@9IMP,Cancelled,NaN
2,NORMAL,N,NORMAL,-nul-,N,-nul-,-nul-,NaN
5,.,N,.,-nul-,Y,-nul-,-nul-,NaN
6,2.8,N,2.8,-nul-,N,-nul-,-nul-,NaN
...,...,...,...,...,...,...,...,...
721030,109,N,109,-nul-,N,-nul-,-nul-,NaN
721031,11,N,11,-nul-,N,-nul-,-nul-,NaN
721032,.,N,.,-nul-,Y,-nul-,-nul-,NaN
721033,.,N,.,-nul-,Y,-nul-,-nul-,NaN
721035,.,N,.,-nul-,Y,-nul-,-nul-,NaN

In [155]:
dlmdata4['Result Cancelled'].unique()

array(['Y', 'N'], dtype=object)

In [156]:
dlmdata4['Canceled If @9'].unique()

array(['-nul-', 'Cancelled', '@1ESP', '@1CRP', '@1PHO', '@UMIC', '@1FSA',
       '@1SHA', '@IGE3', '@1PRA', '@1ESA', '@1AKP', '@1LHA', '@1PRP',
       '@1LHP', '@1TR1', '@1OB4', '@1PGA', '@SRMC', '@1PGP', '@1FSP',
       '@IGE2', '@1SHP', '@1OB2', '@IGE1', '@3SGR', '@2C94', '@1OB1',
       '@1OHC', '@1OB3', '@1UTC', '@1SUB', '@1NON', '@1OB5', '@1COL',
       '@1CRS'], dtype=object)

In [157]:
dlmdata5 = dlmdata4.copy()
dlmdata5['Ultimately Cancelled'] = np.select(condlist = [(dlmdata5['Result Cancelled'] == 'Y') | (dlmdata5['Result Message'].str.contains('@9')),
                                              (dlmdata5['Result Cancelled'] == 'N') & (dlmdata5['Canceled If @9'] != 'Cancelled')],
                                  choicelist = [1,0], default = np.nan)
dlmdata5['Ultimately Cancelled'].unique()
dlmdata5['Ultimately Cancelled'] = dlmdata5['Ultimately Cancelled'].astype(int)

###Find out the difference between 'Result Cancelled' and '@9' and what all the other codes mean.
Is one cancelled by the ordering provider and the other cancelled by the lab?
i.e. Is one prior to specimen collection and the other after?
I removed all but LDL particle size from lipoprotein profile as I assumed lack of FDA clearance would mean many null results from there. Knowing the @codes may be a more accurate way of handling that.
###How come @9 doesn't always translate to 'Cancelled'? e.g. '@9DUPL' and '@9CONT'

In [51]:
dlmdata5[dlmdata5['Canned Result Message Code'] != dlmdata5['Result Message']][['Result Text', 'Modified Result',
       'New Result Text', 'Canned Result Message Code', 'Result Cancelled',
       'Result Message', 'Canceled If @9', 'Cancellation Reason']]

,Result Text,Modified Result,New Result Text,Canned Result Message Code,Result Cancelled,Result Message,Canceled If @9,Cancellation Reason
3520,-nul-,Y,-NUL-,-nul-,N,@9CONT,-nul-,NaN
107286,-nul-,Y,-NUL-,-nul-,N,@(CON,-nul-,NaN
123525,-nul-,N,-NUL-,-nul-,N,@9DUPL,-nul-,NaN
203749,-nul-,N,-NUL-,-nul-,N,@9DUPL,-nul-,NaN
237124,-nul-,N,-NUL-,-nul-,N,@9DUPL,-nul-,NaN
306006,-nul-,N,-NUL-,-nul-,N,@I9IMP,-nul-,NaN
313188,1,N,1,@UMIC,N,@UMIC.,@UMIC,NaN
349520,-nul-,N,-NUL-,-nul-,N,@9DUPL,-nul-,NaN
367844,-nul-,N,-NUL-,@9IMP,N,@9IMP .,Cancelled,NaN
382486,-nul-,N,-NUL-,-nul-,N,@9DUPL,-nul-,NaN
385696,-nul-,Y,-NUL-,-nul-,N,@9con,-nul-,NaN
432630,-nul-,N,-NUL-,-nul-,N,@QNS,-nul-,NaN
483576,-nul-,Y,-NUL-,-nul-,N,@PCON,-nul-,NaN
524073,-nul-,N,-NUL-,-nul-,N,@9DUPL,-nul-,NaN
578814,-nul-,Y,-NUL-,-nul-,N,@IMP,-nul-,NaN
584183,-nul-,N,-NUL-,-nul-,N,@9DUPL,-nul-,NaN
587303,-nul-,N,-NUL-,-nul-,N,@9DUPL,-nul-,NaN
599222,-nul-,N,-NUL-,-nul-,N,@9DUPL,-nul-,NaN
625855,-nul-,N,-NUL-,-nul-,N,@9DUPL,-nul-,NaN
667199,-nul-,N,-NUL-,-nul-,N,@9DUPL,-nul-,NaN

Can drop 'Canned Result Message Code'

In [52]:
dlmdata5['Old Result Text'] = dlmdata5['Result Text'].str.upper()

In [53]:
dlmdata5[['Old Result Text', 'New Result Text']][dlmdata5['Old Result Text'] != dlmdata5['New Result Text']]

Empty DataFrame
Columns: [Old Result Text, New Result Text]
Index: []

Can drop 'New Result Text'

In [54]:
dlmdata5['Cancellation Reason'].unique()

array([nan])

Can drop 'Cancellation Reason'

In [158]:
dlmdata5 = dlmdata5[['Designated Workstation', 'Test Name', 'Result Name', 'Protocol ID',
       'Order Number', 'Order Clinic Code', 'Order Clinic Patient Type',
       'Order Doctor Code', 'Patient Code', 'Result Text', 'Modified Result',
       'Result Message', 'Result Cancelled',
        'Canceled If @9', 'Ultimately Cancelled', 'Cancelled Date Time',
        'Ordered Date Time', 'Collection Date Time',
       'Receiving Date Time', 'Resulted Date Time', 'Verify Date Time']]

In [159]:
DotResults = dlmdata5[dlmdata5['Result Text'] == '.']
NullResults = dlmdata5[dlmdata5['Result Text'] == '-nul-']

In [160]:
DotResults[DotResults['Result Cancelled'] =='Y']

,Designated Workstation,Test Name,Result Name,Protocol ID,Order Number,Order Clinic Code,Order Clinic Patient Type,Order Doctor Code,Patient Code,Result Text,...,Result Message,Result Cancelled,Canceled If @9,Ultimately Cancelled,Cancelled Date Time,Ordered Date Time,Collection Date Time,Receiving Date Time,Resulted Date Time,Verify Date Time
0,URINALYSIS AUWI,Urinalysis,Unidentified Crystals,09-I-0102,R9183098,5NW,Inpatient,ALHMA,3684,.,...,-nul-,Y,-nul-,1,NaN,3/18/2022 8:46,3/18/2022 9:38,3/18/2022 9:45,3/18/2022 8:47,3/18/2022 8:47
5,URINALYSIS AUWI,Urinalysis,Transitional Epithelial,000201-I,S0050380,EXT,Outpatient,ARRLA,6920,.,...,-nul-,Y,-nul-,1,NaN,4/5/2022 0:01,4/5/2022 14:48,4/5/2022 14:48,4/5/2022 0:06,4/5/2022 0:06
11,URINALYSIS AUWI,Urinalysis,Renal Cell Casts,18-C-0135,S0068808,3NE,Inpatient,STOA0,7110,.,...,-nul-,Y,-nul-,1,NaN,4/6/2022 15:45,4/6/2022 16:10,4/6/2022 16:17,4/6/2022 15:45,4/6/2022 15:45
24,URINALYSIS AUWI,Urinalysis,Mucus,19-C-0085,S1120547,OP12,Outpatient,KANJE,6420,.,...,-nul-,Y,-nul-,1,5/23/2022 1:05,5/12/2022 0:01,5/12/2022 0:00,NaN,5/12/2022 0:11,5/12/2022 0:11
28,URINALYSIS AUWI,Urinalysis,Crystal Check AUWi,08-C-0079,R9088899,3SEDH,Outpatient,DERJO,1777,.,...,-nul-,Y,-nul-,1,NaN,3/8/2022 8:07,3/8/2022 8:26,3/8/2022 8:42,3/8/2022 8:08,3/8/2022 8:08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
721026,URINALYSIS AUWI,Urinalysis,Cystine Crystals,15-N-0126,R9293242,5SWDH,Outpatient,SMIBR,7399,.,...,-nul-,Y,-nul-,1,NaN,3/29/2022 8:41,3/29/2022 10:25,3/29/2022 10:37,3/29/2022 8:42,3/29/2022 8:42
721029,URINALYSIS AUWI,Urinalysis,Calcium Phosphate Crystals,21-C-0032E,R9230423,1NW,Inpatient,0VAWI,7439,.,...,-nul-,Y,-nul-,1,NaN,3/23/2022 0:01,3/23/2022 4:45,3/23/2022 5:14,3/23/2022 0:07,3/23/2022 0:07
721032,URINALYSIS AUWI,Urinalysis,Calcium Carbonate Crystals,18-C-0135,R9150056,OP12,Outpatient,DIMDI,5747,.,...,-nul-,Y,-nul-,1,NaN,3/15/2022 0:00,3/15/2022 8:14,3/15/2022 8:30,3/15/2022 0:01,3/15/2022 0:01
721033,URINALYSIS AUWI,Urinalysis,Renal Cell Casts,03-N-0164,R9210193,7SW-N,Inpatient,JUDSA,6174,.,...,-nul-,Y,-nul-,1,NaN,3/21/2022 0:00,3/21/2022 5:38,3/21/2022 6:13,3/21/2022 0:03,3/21/2022 0:03
721035,URINALYSIS AUWI,Urinalysis,Transitional Epithelial,21-C-0032E,S0070599,3SWS1,Inpatient,0VAWI,7439,.,...,-nul-,Y,-nul-,1,NaN,4/7/2022 0:01,4/7/2022 4:42,4/7/2022 8:15,4/7/2022 0:12,4/7/2022 0:12

In [161]:
DotResults[DotResults['Result Cancelled'] =='N']

,Designated Workstation,Test Name,Result Name,Protocol ID,Order Number,Order Clinic Code,Order Clinic Patient Type,Order Doctor Code,Patient Code,Result Text,...,Result Message,Result Cancelled,Canceled If @9,Ultimately Cancelled,Cancelled Date Time,Ordered Date Time,Collection Date Time,Receiving Date Time,Resulted Date Time,Verify Date Time
9880,URINALYSIS AUWI,Urinalysis,Hyaline Casts,21-C-0032E,S0070606,3SWS1,Inpatient,0AMRO,7439,.,...,-nul-,N,-nul-,0,NaN,4/7/2022 0:01,4/7/2022 4:46,NaN,4/7/2022 0:12,NaN
20718,URINALYSIS AUWI,Urinalysis,Hyaline Casts,93-I-0119,S1066040,1H-PE,Outpatient,FREAA,3385,.,...,-nul-,N,-nul-,0,NaN,5/6/2022 15:32,5/6/2022 15:57,NaN,5/6/2022 15:33,NaN
21408,URINALYSIS AUWI,Urinalysis,Bacteria,15-C-0087,R9074164,OP3,Outpatient,DOLRE,4067,.,...,-nul-,N,-nul-,0,NaN,3/7/2022 10:07,3/7/2022 10:31,NaN,3/7/2022 10:07,NaN
28556,URINALYSIS AUWI,Urinalysis,Hyaline Casts,01-C-0129,R9246264,3SE-N,Inpatient,ROSM0,8243,.,...,-nul-,N,-nul-,0,NaN,3/24/2022 16:40,3/24/2022 18:36,NaN,3/24/2022 16:40,NaN
29971,URINALYSIS AUWI,Urinalysis,"RBC, Urine",21-C-0032E,S0080272,3SWS1,Inpatient,0VAWI,7439,.,...,-nul-,N,-nul-,0,NaN,4/8/2022 0:00,4/8/2022 16:13,NaN,4/8/2022 0:07,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
699589,URINALYSIS AUWI,Urinalysis,"WBC, Urine",93-I-0119,S1066040,1H-PE,Outpatient,FREAA,3385,.,...,-nul-,N,-nul-,0,NaN,5/6/2022 15:32,5/6/2022 15:57,NaN,5/6/2022 15:33,NaN
707513,URINALYSIS AUWI,Urinalysis,"WBC, Urine",01-C-0129,R9285196,3SE-N,Inpatient,KAPVI,8243,.,...,-nul-,N,-nul-,0,NaN,3/28/2022 17:01,3/28/2022 18:40,NaN,3/28/2022 17:03,NaN
711318,URINALYSIS AUWI,Urinalysis,Hyaline Casts,21-C-0032E,S0080273,3SWS1,Inpatient,0AMRO,7439,.,...,-nul-,N,-nul-,0,NaN,4/8/2022 0:00,4/8/2022 16:13,NaN,4/8/2022 0:07,NaN
714346,URINALYSIS AUWI,Urinalysis,"RBC, Urine",21-C-0032E,S0100025,3SWS1,Inpatient,0VAWI,7439,.,...,-nul-,N,-nul-,0,NaN,4/10/2022 0:00,4/10/2022 3:52,NaN,4/10/2022 0:01,NaN
715526,URINALYSIS AUWI,Urinalysis,Squamous Epithelial,01-C-0129,R9246264,3SE-N,Inpatient,ROSM0,8243,.,...,-nul-,N,-nul-,0,NaN,3/24/2022 16:40,3/24/2022 18:36,NaN,3/24/2022 16:40,NaN

In [59]:
DotResults[DotResults['Result Cancelled'] =='N']['Receiving Date Time'].unique()

array([nan], dtype=object)

In [60]:
DotResults[DotResults['Result Cancelled'] =='N']['Test Name'].unique()

array(['Urinalysis'], dtype=object)

It seems that Dot Results are either cancelled (?by the provider) or not received (?another mechanism by which tests are cancelled in accessioning). The latter are all urinalysis panel tests that may not have been required.

###Find out if dot results and cancelling results are two ways that accessioning handles tests cancelled or not requested from a panel by the provider.

For now I will remove Dot Results as it seems they represent specimens/tests that were not received in the lab.

In [61]:
NullResults

,Designated Workstation,Test Name,Result Name,Protocol ID,Order Number,Order Clinic Code,Order Clinic Patient Type,Order Doctor Code,Patient Code,Result Text,...,Result Message,Result Cancelled,Canceled If @9,Ultimately Cancelled,Cancelled Date Time,Ordered Date Time,Collection Date Time,Receiving Date Time,Resulted Date Time,Verify Date Time
1,URINALYSIS AUWI,Urinalysis,Squamous Epithelial,15-C-0087,S1165215,OP3,Outpatient,DOLRE,8214,-nul-,...,@9IMP,N,Cancelled,1,NaN,5/16/2022 8:28,5/16/2022 8:32,5/16/2022 8:39,5/16/2022 9:09,5/16/2022 9:16
229,ABBOTT CI8200,Acute Care Panel,Creatinine,20-CC-0113,S0194477,5SWDH,Outpatient,SUFAN,1699,-nul-,...,@9DUP,N,Cancelled,1,NaN,4/19/2022 13:04,4/19/2022 8:16,4/19/2022 13:10,4/19/2022 13:11,4/19/2022 13:13
232,ABBOTT CI8200,"Immunoglobulins, Quantitative",IgG,10-C-0066,R6109788,OP12,Outpatient,KRERO,4544,-nul-,...,@9LBN,N,Cancelled,1,NaN,12/10/2021 14:07,12/9/2021 9:00,12/10/2021 14:29,3/8/2022 11:19,3/8/2022 11:21
1485,MASS SPEC,"Androstenedione, Serum","Androstenedione, Serum",06-CH-0011,S1090001,5NW,Inpatient,0KLEE,3338,-nul-,...,@9IMP,N,Cancelled,1,NaN,5/8/2022 19:00,5/9/2022 1:01,5/9/2022 1:16,5/10/2022 8:45,5/10/2022 8:45
1762,ABBOTT CI8200,Acute Care Panel,Potassium,13-C-0176,R9110214,3NW,Inpatient,JOYST,6752,-nul-,...,@9IMP,N,Cancelled,1,NaN,3/11/2022 0:00,3/11/2022 6:19,3/11/2022 6:38,3/11/2022 7:12,3/11/2022 7:18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
719563,ABBOTT CI8200,Hepatic Panel,Aspartate Aminotransferase,13-I-0157,S0060189,5SW-N,Inpatient,GARJ1,5132,-nul-,...,@9IMP,N,Cancelled,1,NaN,4/6/2022 0:01,4/6/2022 5:15,4/6/2022 5:39,4/6/2022 5:39,4/6/2022 5:41
719947,URINALYSIS AUWI,Urinalysis,"Protein, Urine.",00-N-0140,R9157909,7SW-N,Inpatient,PIPCH,1316,-nul-,...,@9DUP,N,Cancelled,1,NaN,3/15/2022 11:41,3/15/2022 10:16,3/15/2022 13:40,3/15/2022 13:41,3/15/2022 13:47
720155,MASS SPEC,"Cortisol & Cortisone, Free, 24 hr Urine","Cortisone, Free, Urine",01-D-0184,R9038908,5SWDH,Outpatient,HARIR,1173,-nul-,...,@9CAN,N,Cancelled,1,NaN,3/3/2022 9:47,3/3/2022 10:04,3/3/2022 10:34,3/4/2022 15:10,3/4/2022 15:11
720618,URINALYSIS AUWI,Urinalysis,Squamous Epithelial,21-C-0006,S1038415,OP3,Outpatient,SULMO,6370,-nul-,...,@9IMP,N,Cancelled,1,NaN,5/3/2022 9:43,5/3/2022 14:17,5/3/2022 14:37,5/3/2022 14:43,5/3/2022 14:51
720819,URINALYSIS AUWI,Urinalysis,Urobilinogen,15-C-0087,R9074164,OP3,Outpatient,DOLRE,4067,-nul-,...,-nul-,N,-nul-,0,NaN,3/7/2022 10:07,3/7/2022 10:31,NaN,NaN,NaN

In [165]:
NullResults[NullResults['Ultimately Cancelled']==0]

,Designated Workstation,Test Name,Result Name,Protocol ID,Order Number,Order Clinic Code,Order Clinic Patient Type,Order Doctor Code,Patient Code,Result Text,...,Result Message,Result Cancelled,Canceled If @9,Ultimately Cancelled,Cancelled Date Time,Ordered Date Time,Collection Date Time,Receiving Date Time,Resulted Date Time,Verify Date Time
3584,URINALYSIS AUWI,Urinalysis,Nitrite,01-C-0038,R9010360,3NW,Inpatient,RAMR1,4755,-nul-,...,-nul-,N,-nul-,0,NaN,3/1/2022 0:00,3/1/2022 5:51,NaN,NaN,NaN
4702,"PEP, IFE, & CRYO",Oligo. Banding CSF and Serum,"Oligoclonal Bands, CSF",15-N-0125,S0059156,OP5,Outpatient,SMIBR,7932,-nul-,...,@1OB4,N,@1OB4,0,NaN,4/5/2022 11:03,4/5/2022 13:52,4/5/2022 14:27,4/11/2022 12:58,4/11/2022 12:59
5882,ABBOTT CI8200,Creatinine Clearance,Creatinine,89-C-0086,R9024839,OP3,Outpatient,RYABE,1394,-nul-,...,@SRMC,N,@SRMC,0,NaN,3/2/2022 8:54,3/2/2022 9:08,3/2/2022 9:26,3/3/2022 9:07,3/3/2022 9:07
7208,URINALYSIS AUWI,Urinalysis,"pH, Urine.",21-C-0032E,S0070606,3SWS1,Inpatient,0AMRO,7439,-nul-,...,-nul-,N,-nul-,0,NaN,4/7/2022 0:01,4/7/2022 4:46,NaN,NaN,NaN
8037,URINALYSIS AUWI,Urinalysis,Bilirubin,14-AA-0181,S1206954,1H-AL,Outpatient,VINTO,4426,-nul-,...,-nul-,N,-nul-,0,NaN,5/20/2022 10:50,5/20/2022 11:05,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
711040,URINALYSIS AUWI,Urinalysis,Clarity,14-AA-0181,S1206954,1H-AL,Outpatient,VINTO,4426,-nul-,...,-nul-,N,-nul-,0,NaN,5/20/2022 10:50,5/20/2022 11:05,NaN,NaN,NaN
711199,URINALYSIS AUWI,Urinalysis,Leukocyte Esterase,93-I-0119,S1233154,OP11,Outpatient,DEGMA,4888,-nul-,...,-nul-,N,-nul-,0,NaN,5/23/2022 7:37,5/23/2022 7:56,NaN,NaN,NaN
712173,URINALYSIS AUWI,Urinalysis,"Specific Gravity, Urine.",21-C-0032E,S0090062,3SWS1,Inpatient,0VAWI,7439,-nul-,...,-nul-,N,-nul-,0,NaN,4/9/2022 0:00,4/9/2022 4:02,NaN,NaN,NaN
715239,ABBOTT CI8200,Acute Care Panel,Glucose,04-C-0165,S0220284,3NW,Inpatient,STEPA,6365,-nul-,...,@2C94,N,@2C94,0,NaN,4/22/2022 0:01,4/22/2022 5:41,4/22/2022 6:05,4/22/2022 6:59,4/22/2022 7:06
720819,URINALYSIS AUWI,Urinalysis,Urobilinogen,15-C-0087,R9074164,OP3,Outpatient,DOLRE,4067,-nul-,...,-nul-,N,-nul-,0,NaN,3/7/2022 10:07,3/7/2022 10:31,NaN,NaN,NaN

In [63]:
NullResults[(NullResults['Result Message'] == '-nul-')]['Receiving Date Time'].unique()

array([nan], dtype=object)

Null results are either have a result message code or are not received, resulted or verified.
###Need to understand the codes.

In [162]:
dlmdata5 = dlmdata5[dlmdata5['Result Text'] != '.']

In [166]:
print('There are now ' +str(dlmdata5.shape[0]) + ' data entries.')

There are now 412159 data entries.

#Dates

It is known that some test orders are put in many days, weeks or months before the specimen is collected. I'll limit this data set to only those specimens collected in the specified time period.

First I need to check if the data is in the correct format and convert it if necessary.

In [167]:
dlmdata5.dtypes

Designated Workstation       object
Test Name                    object
Result Name                  object
Protocol ID                  object
Order Number                 object
Order Clinic Code            object
Order Clinic Patient Type    object
Order Doctor Code            object
Patient Code                  int64
Result Text                  object
Modified Result              object
Result Message               object
Result Cancelled             object
Canceled If @9               object
Ultimately Cancelled          int64
Cancelled Date Time          object
Ordered Date Time            object
Collection Date Time         object
Receiving Date Time          object
Resulted Date Time           object
Verify Date Time             object
dtype: object

The Date Time columns are not in the correct format. It takes a long time for the computer to change each column's format, so it's best to choose those that really need to be changed.

Collection Date Time may be best as this is when labels are printed for samples, which have presumably just been drawn.

Receiving Date Time should be soon after that and may be a better option in case tubes are sometimes pre-labelled.

In [168]:
dlmdata5[['Test Name', 'Result Name','Result Text',
       'Result Cancelled', 'Ultimately Cancelled', 'Ordered Date Time',
       'Collection Date Time', 'Receiving Date Time', 'Resulted Date Time',
       'Verify Date Time']].head(10)

,Test Name,Result Name,Result Text,Result Cancelled,Ultimately Cancelled,Ordered Date Time,Collection Date Time,Receiving Date Time,Resulted Date Time,Verify Date Time
1,Urinalysis,Squamous Epithelial,-nul-,N,1,5/16/2022 8:28,5/16/2022 8:32,5/16/2022 8:39,5/16/2022 9:09,5/16/2022 9:16
2,Urinalysis,Urobilinogen,NORMAL,N,0,4/28/2022 10:10,4/28/2022 11:04,4/28/2022 11:10,4/28/2022 11:16,4/28/2022 11:16
6,Mineral Panel,"Phosphorus, Inorganic",2.8,N,0,3/21/2022 11:18,3/21/2022 11:28,3/21/2022 11:52,3/21/2022 12:20,3/21/2022 12:23
8,Acute Care Panel,Potassium,7.7,N,0,3/29/2022 11:00,3/29/2022 17:24,3/29/2022 17:29,3/29/2022 18:04,3/29/2022 19:08
10,Urinalysis,Bacteria,0,N,0,4/18/2022 11:24,4/18/2022 11:40,4/18/2022 12:05,4/18/2022 12:19,4/18/2022 12:19
12,Hepatic Panel,"Bilirubin, Total",0.6,N,0,3/15/2022 9:13,3/15/2022 10:02,3/15/2022 10:24,3/15/2022 10:57,3/15/2022 11:03
13,Urinalysis,Bilirubin,NEGATIVE,N,0,5/14/2022 0:00,5/14/2022 0:13,5/14/2022 0:32,5/14/2022 0:39,5/14/2022 0:39
14,Mineral Panel,Magnesium,1.7,N,0,3/4/2022 10:00,3/4/2022 15:28,3/4/2022 15:38,3/4/2022 16:10,3/4/2022 16:11
15,Urinalysis,Bilirubin,NEGATIVE,N,0,5/16/2022 15:05,5/16/2022 15:21,5/16/2022 15:42,5/16/2022 15:55,5/16/2022 15:55
16,Urinalysis,"pH, Urine.",6.5,N,0,4/20/2022 8:14,4/20/2022 8:43,4/20/2022 8:52,4/20/2022 9:05,4/20/2022 9:05

In [169]:
dlmdata6 = dlmdata5.copy()
dlmdata6['Collection Date Time'] = pd.to_datetime(dlmdata6['Collection Date Time'])
dlmdata6['Receiving Date Time'] = pd.to_datetime(dlmdata6['Receiving Date Time'])

It might make sense to exclude the remaining tests that were never received, but first need to find out why they have a -nul- result instead of a (.) result.

In [170]:
excldata1 = dlmdata6.copy()
excldata1 = excldata1[(excldata1['Collection Date Time'] >='2022-06-01 00:00:00') | (excldata1['Collection Date Time'] <'2022-03-01 00:00:00')]
excldata2 = excldata1[['Test Name', 'Result Name', 'Order Number','Modified Result','Result Text','Result Cancelled', 'Collection Date Time', 'Ordered Date Time', 'Receiving Date Time',
                      'Resulted Date Time', 'Verify Date Time']]
excldata2.head(15)

,Test Name,Result Name,Order Number,Modified Result,Result Text,Result Cancelled,Collection Date Time,Ordered Date Time,Receiving Date Time,Resulted Date Time,Verify Date Time
232,"Immunoglobulins, Quantitative",IgG,R6109788,Y,-nul-,N,2021-12-09 09:00:00,12/10/2021 14:07,2021-12-10 14:29:00,3/8/2022 11:19,3/8/2022 11:21
427,Immunoglobulin Free Light Chains,IgM,R8285109,N,51,N,2022-02-28 09:22:00,2/28/2022 8:41,2022-02-28 10:05:00,2/28/2022 10:19,2/28/2022 10:19
833,Anti-EBV Antibody Panel,EBNA,R9294076,N,Positive,N,2021-03-29 14:27:00,3/29/2022 11:21,2022-03-29 14:27:00,4/7/2022 15:04,4/7/2022 15:18
897,"Electrophoresis, Protein, Serum",Alpha 1,R8262264,N,0.2,N,2022-02-26 05:36:00,2/26/2022 2:29,2022-02-26 06:00:00,3/1/2022 11:30,3/1/2022 14:20
1189,"Immunofixation Electrophoresis, Serum",Gamma,R8280030,N,0.4,N,2022-02-28 06:46:00,2/28/2022 0:00,2022-02-28 07:12:00,3/1/2022 12:22,3/3/2022 15:23
2030,Anti-EBV Antibody Panel,EBVCA-IgM,R9294065,N,Negative,N,2021-03-29 14:27:00,3/29/2022 11:18,2022-03-29 14:27:00,4/7/2022 15:15,4/7/2022 15:18
2584,Alpha-1-Antitrypsin,Alpha-1-Antitrypsin,R8254969,N,116,N,2022-02-25 10:37:00,2/25/2022 9:51,2022-02-25 10:54:00,3/1/2022 9:40,3/1/2022 9:36
4491,"Immunofixation Electrophoresis, Serum",IgG,R8250183,N,3198,N,2022-02-25 05:36:00,2/25/2022 14:55,2022-02-25 06:17:00,2/25/2022 15:09,2/25/2022 15:10
6342,Rheumatoid Factor,Rheumatoid Factor,R8285548,N,<10,N,2022-02-28 10:24:00,2/28/2022 9:33,2022-02-28 10:49:00,3/1/2022 9:31,3/1/2022 9:23
8535,Anti-EBV Antibody Panel,EBVCA-IgM,R9293989,N,Negative,N,2021-03-29 14:29:00,3/29/2022 10:58,2022-03-29 14:29:00,4/7/2022 15:12,4/7/2022 15:18
10634,Anti-EBV Antibody Panel,EBNA,R9294030,N,Positive,N,2021-03-29 14:28:00,3/29/2022 11:08,2022-03-29 14:28:00,4/7/2022 15:07,4/7/2022 15:18
12723,Anti-S SARS-CoV-2 Antibodies,Anti-S SARS-CoV-2 Antibodies,R9016600,N,496.1,N,2022-02-28 15:37:00,3/1/2022 13:27,2022-03-01 15:40:00,3/2/2022 7:27,3/2/2022 8:44
13111,"Androstenedione, Serum","Androstenedione, Serum",R8232607,N,-nul-,N,2022-02-23 08:28:00,2/23/2022 8:03,2022-02-23 09:20:00,3/4/2022 9:59,3/4/2022 10:01
15702,"Immunofixation Electrophoresis, Serum",IgA,R8250183,N,521,N,2022-02-25 05:36:00,2/25/2022 14:55,2022-02-25 06:17:00,2/25/2022 15:09,2/25/2022 15:10
17857,Anti-EBV Antibody Panel,EBNA,R9294053,N,Positive,N,2021-03-29 14:27:00,3/29/2022 11:12,2022-03-29 14:27:00,4/4/2022 13:39,4/4/2022 14:35

Some tests are definitely given labels long before the sample is collected. Up to a year!!

In [171]:
excldata3 = dlmdata6.copy()
excldata3 = excldata3[(excldata3['Receiving Date Time'] >='2022-06-01 00:00:00') | (excldata3['Receiving Date Time'] <'2022-03-01 00:00:00')]
excldata4 = excldata3[['Test Name', 'Result Name', 'Order Number','Modified Result','Result Text','Result Cancelled', 'Collection Date Time', 'Ordered Date Time', 'Receiving Date Time',
                      'Resulted Date Time', 'Verify Date Time']]
excldata2.head(15)

,Test Name,Result Name,Order Number,Modified Result,Result Text,Result Cancelled,Collection Date Time,Ordered Date Time,Receiving Date Time,Resulted Date Time,Verify Date Time
232,"Immunoglobulins, Quantitative",IgG,R6109788,Y,-nul-,N,2021-12-09 09:00:00,12/10/2021 14:07,2021-12-10 14:29:00,3/8/2022 11:19,3/8/2022 11:21
427,Immunoglobulin Free Light Chains,IgM,R8285109,N,51,N,2022-02-28 09:22:00,2/28/2022 8:41,2022-02-28 10:05:00,2/28/2022 10:19,2/28/2022 10:19
833,Anti-EBV Antibody Panel,EBNA,R9294076,N,Positive,N,2021-03-29 14:27:00,3/29/2022 11:21,2022-03-29 14:27:00,4/7/2022 15:04,4/7/2022 15:18
897,"Electrophoresis, Protein, Serum",Alpha 1,R8262264,N,0.2,N,2022-02-26 05:36:00,2/26/2022 2:29,2022-02-26 06:00:00,3/1/2022 11:30,3/1/2022 14:20
1189,"Immunofixation Electrophoresis, Serum",Gamma,R8280030,N,0.4,N,2022-02-28 06:46:00,2/28/2022 0:00,2022-02-28 07:12:00,3/1/2022 12:22,3/3/2022 15:23
2030,Anti-EBV Antibody Panel,EBVCA-IgM,R9294065,N,Negative,N,2021-03-29 14:27:00,3/29/2022 11:18,2022-03-29 14:27:00,4/7/2022 15:15,4/7/2022 15:18
2584,Alpha-1-Antitrypsin,Alpha-1-Antitrypsin,R8254969,N,116,N,2022-02-25 10:37:00,2/25/2022 9:51,2022-02-25 10:54:00,3/1/2022 9:40,3/1/2022 9:36
4491,"Immunofixation Electrophoresis, Serum",IgG,R8250183,N,3198,N,2022-02-25 05:36:00,2/25/2022 14:55,2022-02-25 06:17:00,2/25/2022 15:09,2/25/2022 15:10
6342,Rheumatoid Factor,Rheumatoid Factor,R8285548,N,<10,N,2022-02-28 10:24:00,2/28/2022 9:33,2022-02-28 10:49:00,3/1/2022 9:31,3/1/2022 9:23
8535,Anti-EBV Antibody Panel,EBVCA-IgM,R9293989,N,Negative,N,2021-03-29 14:29:00,3/29/2022 10:58,2022-03-29 14:29:00,4/7/2022 15:12,4/7/2022 15:18
10634,Anti-EBV Antibody Panel,EBNA,R9294030,N,Positive,N,2021-03-29 14:28:00,3/29/2022 11:08,2022-03-29 14:28:00,4/7/2022 15:07,4/7/2022 15:18
12723,Anti-S SARS-CoV-2 Antibodies,Anti-S SARS-CoV-2 Antibodies,R9016600,N,496.1,N,2022-02-28 15:37:00,3/1/2022 13:27,2022-03-01 15:40:00,3/2/2022 7:27,3/2/2022 8:44
13111,"Androstenedione, Serum","Androstenedione, Serum",R8232607,N,-nul-,N,2022-02-23 08:28:00,2/23/2022 8:03,2022-02-23 09:20:00,3/4/2022 9:59,3/4/2022 10:01
15702,"Immunofixation Electrophoresis, Serum",IgA,R8250183,N,521,N,2022-02-25 05:36:00,2/25/2022 14:55,2022-02-25 06:17:00,2/25/2022 15:09,2/25/2022 15:10
17857,Anti-EBV Antibody Panel,EBNA,R9294053,N,Positive,N,2021-03-29 14:27:00,3/29/2022 11:12,2022-03-29 14:27:00,4/4/2022 13:39,4/4/2022 14:35

Receiving Date seems a much better option. I will allow a receiving date from Feb 23 to accommodate batch testing.

Clearly the extract was limited to all verified by end of May as nothing came up after that date.

### Need to decide what to do about tests not received

In [172]:
dlmdata6 = dlmdata6[(dlmdata6['Receiving Date Time'].isnull()) | (dlmdata6['Receiving Date Time'] <'2022-06-01 00:00:00') & (dlmdata6['Receiving Date Time'] >='2022-02-22 00:00:00')]

In [173]:
print('There are now ' +str(dlmdata6.shape[0]) + ' data entries for the 3 month collection period.')

There are now 412130 data entries for the 3 month collection period.

#Final DataFrame

In [174]:
dlmdata6.isna().sum()

Designated Workstation            0
Test Name                         0
Result Name                       0
Protocol ID                       0
Order Number                      0
Order Clinic Code                 0
Order Clinic Patient Type         0
Order Doctor Code                 0
Patient Code                      0
Result Text                       0
Modified Result                   0
Result Message                    0
Result Cancelled                  0
Canceled If @9                    0
Ultimately Cancelled              0
Cancelled Date Time          411811
Ordered Date Time                 0
Collection Date Time              0
Receiving Date Time             277
Resulted Date Time              260
Verify Date Time                267
dtype: int64

In [175]:
dlmdata6 = dlmdata6.reset_index(drop=True)

#Save data

In [176]:
dlmdata6.to_csv('Outputs/dlmdata.csv', index = False)